// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using To_DoListAppication.ToDoDBContext;

#nullable disable

namespace To_DoListAppication.Migrations
{
    [DbContext(typeof(TODoDBContext))]
    [Migration("20240605121300_AllMigration")]
    partial class AllMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("To_DoListAppication.Models.SignInModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("mobile")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("signInModels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            email = "ch@gmail.com",
                            mobile = 6574837373L,
                            name = "ramesh",
                            password = "111"
                        });
                });

            modelBuilder.Entity("To_DoListAppication.Models.WorkRecordModel", b =>
                {
                    b.Property<int>("workId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("workId"), 1L, 1);

                    b.Property<string>("IsCompleted")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("dateOfWork")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("workDetails")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("workName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("workId");

                    b.ToTable("workRecordModels", (string)null);

                    b.HasData(
                        new
                        {
                            workId = 1,
                            IsCompleted = "Yes",
                            dateOfWork = new DateTime(2024, 6, 5, 17, 42, 59, 818, DateTimeKind.Local).AddTicks(3001),
                            userEmail = "ch@gmail.com",
                            workDetails = "Add  model folder. add a class",
                            workName = "tocreate model"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
